## Write a Numpy program to compute the multiplication of two given matrixes

In [3]:
import numpy as np 
mat1=np.array([2,3,4,5]).reshape(2,2)
mat2=np.array([5,6,7,8]).reshape(2,2)
mat3=np.dot(mat1,mat2)
print(mat3)

[[31 36]
 [55 64]]


## Write a NumPy program to compute the determinant of a given square array

In [7]:
array=np.arange(1,10).reshape(3,3)
if len(array)==len(array[0]):
    print(np.linalg.det(array))


-9.51619735392994e-16


#

## Write a NumPy program to compute the cross product of two given vectors

In [9]:
v1=np.array([10,20,30])
v2=np.array([40,50,60])
print(np.cross(v1,v2))

[-300  600 -300]


## Write a NumPy program to compute the condition number of a given matrix

In [10]:
mat=np.arange(20,29).reshape(3,3)
np.linalg.cond(mat)

9.588326981702584e+16

## Write a NumPy program to compute the inverse of a given matrix

In [11]:
mat=np.arange(20,29).reshape(3,3)
np.linalg.inv(mat)

array([[-3.46430741e+14,  6.92861481e+14, -3.46430741e+14],
       [ 6.92861481e+14, -1.38572296e+15,  6.92861481e+14],
       [-3.46430741e+14,  6.92861481e+14, -3.46430741e+14]])